spring:
  sql:
    init:
      platform: postgres

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
     ddl-auto: 'create-drop'
     dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 50
      pool-name: PostgresDbPool
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${POSTGRES_DATABASE:postgres}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver